name: TEST Publish Helm Charts

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para acceder a todas las versiones y ramas

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm dependency update "$chart" || true
              helm package "$chart" --destination packaged
            fi
          done

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || echo "no gh-pages branch yet"
          git checkout gh-pages || git checkout --orphan gh-pages
          cp -r ../packaged/* .
          rm -f index.yaml

      - name: Generate new index.yaml
        run: |
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Commit and push
        run: |
          git add .
          git commit -m "Update Helm repo index [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
